### PR TITLE
Adding L4E-in-Germany Audio file

### PR DESCRIPTION
**Pull request by pheiduck**
Signed-off-by: pheiduck <pheiduck@github.com>

### CODE REVIEW

**Comment by pheiduck** [comment]
Hm, I have forget the Welcome home

**Comment by pheiduck** [comment]
Will do a reupload

**Comment by LinuxForEveryone** [comment]
Ok, thanks @pheiduck. Standing by!

**Review by pheiduck — COMMENTED** [review]
Latest File is the correct one

**Review by LinuxForEveryone — APPROVED** [review]
You're awesome, thanks for submitting this!

**Pull request merged**
